#goal definition
geometry_msgs/PoseStamped start     # Start pose
geometry_msgs/PoseStamped goal    # Goal pose
geometry_msgs/PoseStamped[] waypoints #Waypoints
string planner     # Name of planner to be used

---
#result definition
nav_msgs/Path plan                        # Path from start to goal
bool success     # is needed??
---
#feedback definition